version: "3.8"

networks:
  working_hands_app:
    driver: bridge

services:
  nginx:
    image: "nginx:stable-alpine"
    networks:
      - working_hands_app
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - mysql
      - php

  php:
    networks:
      - working_hands_app
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  mysql:
    image: "mysql:8.0"
    networks:
      - working_hands_app
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    networks:
      - working_hands_app
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php","/var/www/laravel/artisan"]
    networks:
      - working_hands_app
#  node:
#    image: "node:18-alpine"
#    networks:
#      - working_hands_app
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./client:/var/www/react
#    working_dir: /var/www/react
#    command: "npm run dev"
volumes:
  db_data: